[project]
org-name = "wso2"
version = "0.8.12"
authors = ["WSO2"]
repository = "https://github.com/wso2-ballerina/package-gmail"
keywords = ["gmail","email"]
license = "Apache-2.0"
homepage = "https://wso2.com/"