[package]
org = "ballerinax"
name = "googleapis_gmail"
version = "0.99.3"
authors = ["Ballerina"]
repository = "https://github.com/ballerina-platform/module-ballerinax-googleapis.gmail"
keywords = ["gmail","email"]
license = ["Apache-2.0"]

[build-options]
observabilityIncluded = true

