[package]
distribution = "2201.8.0"
org = "ballerinax"
name = "googleapis.gmail"
version = "4.1.0"
authors = ["Ballerina"]
export = ["googleapis.gmail"]
repository = "https://github.com/ballerina-platform/module-ballerinax-googleapis.gmail"
keywords = ["Communication/Email", "Cost/Free", "Vendor/Google"]
icon = "icon.png"
license = ["Apache-2.0"]

[build-options]
observabilityIncluded = true

[platform.java17]
graalvmCompatible = true
