[package]
org = "ballerinax"
name = "googleapis.gmail"
version = "2.0.0"
export= ["googleapis.gmail", "googleapis.gmail.listener"]
authors = ["Ballerina"]
repository = "https://github.com/ballerina-platform/module-ballerinax-googleapis.gmail"
keywords = ["Communication/Email", "Cost/Free", "Vendor/Google"]
license = ["Apache-2.0"]

[build-options]
observabilityIncluded = true

[[platform.java11.dependency]]
path = "../java-wrapper/build/libs/java-wrapper-0.99.8-SNAPSHOT.jar"
groupId = "org.ballerinalang.googleapis.gmail"
artifactId = "java-wrapper"
version = "0.99.8-SNAPSHOT"
