[package]
org = "ballerinax"
name = "googleapis.gmail"
version = "0.99.12"
export= ["googleapis.gmail", "googleapis.gmail.listener"]
authors = ["Ballerina"]
repository = "https://github.com/ballerina-platform/module-ballerinax-googleapis.gmail"
keywords = ["gmail","email","google","mail"]
license = ["Apache-2.0"]

[build-options]
observabilityIncluded = true

[[platform.java11.dependency]]
path = "../java-wrapper/build/libs/java-wrapper-0.99.12.jar"
groupId = "org.ballerinalang.googleapis.gmail"
artifactId = "java-wrapper"
version = "0.99.12"
