name: Publish Release

on:
  workflow_dispatch:
  repository_dispatch:
    types: [ stdlib-release-pipeline ]

jobs:
  call_workflow:
    name: Run Release Workflow
    if: ${{ github.repository_owner == 'ballerina-platform' }}
    uses: ballerina-platform/ballerina-standard-library/.github/workflows/release-package-connector-template.yml@main
    secrets: inherit
    with:
      package-name: googleapis.gmail
      package-org: ballerinax
      additional-build-flags: "-x :googleapis.gmail-examples:build"
      additional-release-flags: "-x :googleapis.gmail-examples:build"
      additional-publish-flags: "-x :googleapis.gmail-examples:build"
